name: Android APK (Buildozer)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Buildozer
        id: buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        env:
          USER: root        # <-- key fix for "chown: invalid user"
        with:
          workdir: .
          buildozer_version: stable
          command: buildozer -v android debug

      - name: List files (debug)
        run: |
          ls -lah
          ls -lah bin || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: conductor-area-apk
          path: ${{ steps.buildozer.outputs.filename }}
