name: Android APK (Buildozer)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Build using the Buildozer Docker action (no local setup)
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .
          buildozer_version: stable
          buildozer_cmd: buildozer -v android debug

      - name: List files (debug)
        run: |
          ls -lah
          ls -lah bin || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: conductor-area-apk
          path: bin/*.apk
